[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["sathwikmatsa <sathwikmatsa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.7"
petgraph = "0.4.13"
permutohedron = "0.2.4"
